/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as EventsRouteImport } from './routes/events'
import { Route as PanelsRouteImport } from './routes/panels'
import { Route as ApiPublicHooksSyncSpreadsheetsRouteImport } from './routes/api/public/hooks/sync-spreadsheets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelsRoute = PanelsRouteImport.update({
  id: '/panels',
  path: '/panels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncSpreadsheetsRoute =
  ApiPublicHooksSyncSpreadsheetsRouteImport.update({
    id: '/api/public/hooks/sync-spreadsheets',
    path: '/api/public/hooks/sync-spreadsheets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/config': typeof ConfigRoute
  '/events': typeof EventsRoute
  '/panels': typeof PanelsRoute
  '/api/public/hooks/sync-spreadsheets': typeof ApiPublicHooksSyncSpreadsheetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/config': typeof ConfigRoute
  '/events': typeof EventsRoute
  '/panels': typeof PanelsRoute
  '/api/public/hooks/sync-spreadsheets': typeof ApiPublicHooksSyncSpreadsheetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/config': typeof ConfigRoute
  '/events': typeof EventsRoute
  '/panels': typeof PanelsRoute
  '/api/public/hooks/sync-spreadsheets': typeof ApiPublicHooksSyncSpreadsheetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/config'
    | '/events'
    | '/panels'
    | '/api/public/hooks/sync-spreadsheets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/config'
    | '/events'
    | '/panels'
    | '/api/public/hooks/sync-spreadsheets'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/config'
    | '/events'
    | '/panels'
    | '/api/public/hooks/sync-spreadsheets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConfigRoute: typeof ConfigRoute
  EventsRoute: typeof EventsRoute
  PanelsRoute: typeof PanelsRoute
  ApiPublicHooksSyncSpreadsheetsRoute: typeof ApiPublicHooksSyncSpreadsheetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panels': {
      id: '/panels'
      path: '/panels'
      fullPath: '/panels'
      preLoaderRoute: typeof PanelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-spreadsheets': {
      id: '/api/public/hooks/sync-spreadsheets'
      path: '/api/public/hooks/sync-spreadsheets'
      fullPath: '/api/public/hooks/sync-spreadsheets'
      preLoaderRoute: typeof ApiPublicHooksSyncSpreadsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConfigRoute: ConfigRoute,
  EventsRoute: EventsRoute,
  PanelsRoute: PanelsRoute,
  ApiPublicHooksSyncSpreadsheetsRoute: ApiPublicHooksSyncSpreadsheetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
