/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ApiPublicHooksSyncSpreadsheetsRouteImport } from './routes/api/public/hooks/sync-spreadsheets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncSpreadsheetsRoute =
  ApiPublicHooksSyncSpreadsheetsRouteImport.update({
    id: '/api/public/hooks/sync-spreadsheets',
    path: '/api/public/hooks/sync-spreadsheets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/api/public/hooks/sync-spreadsheets': typeof ApiPublicHooksSyncSpreadsheetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/api/public/hooks/sync-spreadsheets': typeof ApiPublicHooksSyncSpreadsheetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/api/public/hooks/sync-spreadsheets': typeof ApiPublicHooksSyncSpreadsheetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/config' | '/api/public/hooks/sync-spreadsheets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/config' | '/api/public/hooks/sync-spreadsheets'
  id: '__root__' | '/' | '/config' | '/api/public/hooks/sync-spreadsheets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  ApiPublicHooksSyncSpreadsheetsRoute: typeof ApiPublicHooksSyncSpreadsheetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-spreadsheets': {
      id: '/api/public/hooks/sync-spreadsheets'
      path: '/api/public/hooks/sync-spreadsheets'
      fullPath: '/api/public/hooks/sync-spreadsheets'
      preLoaderRoute: typeof ApiPublicHooksSyncSpreadsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  ApiPublicHooksSyncSpreadsheetsRoute: ApiPublicHooksSyncSpreadsheetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
